// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReadExcel.Db;

#nullable disable

namespace ReadExcel.Migrations
{
    [DbContext(typeof(DbDataContext))]
    [Migration("20220705044935_master")]
    partial class master
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReadExcel.Model.DataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BISNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BISNumber");

                    b.Property<string>("CDCLabelTemplate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CDCLabelTemplate");

                    b.Property<DateTime>("DateOfUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateOfUpdated");

                    b.Property<string>("DigitsUPCCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DigitsUPCCode");

                    b.Property<string>("HPInternalPN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HPInternalPN");

                    b.Property<string>("ImprintLogo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImprintLogo");

                    b.Property<string>("ImprintSerialNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImprintSerialNo");

                    b.Property<string>("KCC")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KCC");

                    b.Property<string>("MaterialNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MaterialNo");

                    b.Property<string>("OptionPN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OptionPN");

                    b.Property<string>("OverpackLabelTemplate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OverpackLabelTemplate");

                    b.Property<string>("PCAModuleAndInternal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PCAModuleAndInternal");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductCode");

                    b.Property<string>("ProductDescriptione")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductDescriptione");

                    b.Property<string>("ProductLabelTemplate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ProductLabelTemplate");

                    b.Property<string>("Product_No")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Product_No");

                    b.Property<string>("RMN")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RMN");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Remark1");

                    b.Property<string>("Rev")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rev");

                    b.Property<string>("SamePartSNCheck")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SamePartSNCheck");

                    b.Property<string>("SpareNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SpareNo");

                    b.Property<string>("StandardPackQty")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StandardPackQty");

                    b.Property<string>("SupplierPartNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SupplierPartNumber");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("digitsJANCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("digitsJANCode");

                    b.HasKey("Id");

                    b.ToTable("Master_List");
                });
#pragma warning restore 612, 618
        }
    }
}
